#!/usr/bin/ruby

require 'io/console'

def read_input(options_hash)
  prompt = <<~PROMPT
    Input your choice:
    #{
      options_hash.map do |key, value|
        "#{key}) #{value}"
      end.join("\n")
    }

  PROMPT

  puts prompt

  loop do
    input = STDIN.getch
    return input if options_hash.key?(input)

    puts 'Invalid choice'
  end
end

$pr_number = ARGV.first

unless $pr_number
  puts 'Usage: ./ora <pr number> [option]'
  exit 1
end

PATH_OPTIONS = {
  'h' => '/',
  '0' => '/admin/orders',
  '1' => '/products/hdmi-expansion-card',
  '2' => '/products/laptop-diy-13-gen-intel',
  '3' => '/products/laptop-13-gen-intel',
  '4' => '/products/laptop16-diy-amd-7040',
  '5' => '/products/laptop16-amd-7040',
  '6' => '/products/laptop-chromebook-12-gen-intel',
  '7' => '/marketplace/expansion-cards',
  '8' => '/marketplace/laptops'
}.freeze

MODE_OPTIONS = { 
  'o' => 'open',
  'c' => 'copy to clipboard'
}

path = PATH_OPTIONS[read_input(PATH_OPTIONS)]
mode = read_input(MODE_OPTIONS)

puts mode
url = "https://framework-web-qa-pr-#{$pr_number}.herokuapp.com#{path}"
if mode == 'o'
  puts "Opening #{url}"
  `open -a 'Firefox Developer Edition' "#{url}"`
else
  `echo '#{url}' | pbcopy`
  puts "#{url} copied to clipboard"
end
