#!/usr/bin/ruby

require 'io/console'

def read_input(options_hash)
  prompt = <<~PROMPT
    Input your choice:
    #{
      options_hash.map do |key, value|
        "#{key}) #{value}"
      end.join("\n")
    }

  PROMPT

  puts prompt

  loop do
    input = STDIN.getch
    return input if options_hash.key?(input)

    puts 'Invalid choice'
  end
end

$pr_number = ARGV.first

unless $pr_number
  puts 'Usage: ./ora <pr number> [option]'
  exit 1
end

MODE_OPTIONS = { 
  'o' => 'open',
  'c' => 'copy to clipboard'
}

url = "https://framework-web-qa-pr-#{$pr_number}.herokuapp.com"

mode = read_input(MODE_OPTIONS)

if mode == 'o'
  puts "Opening #{url}"
  `open -a 'Firefox Developer Edition' "#{url}"`
else
  `echo '#{url}' | pbcopy`
  puts "#{url} copied to clipboard"
end
